# Generated by Django 2.0.3 on 2018-10-23 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Endast alfanumeriska tecken är tillåtna')])),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('icon', models.CharField(default='tf.svg', max_length=32)),
                ('public', models.BooleanField(default=False)),
                ('forward_limit_days', models.PositiveIntegerField(default=0)),
                ('length_limit_hours', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='slut')),
                ('comment', models.CharField(max_length=128, verbose_name='kommentar')),
                ('bookable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Bookable')),
            ],
            options={
                'verbose_name': 'Bokning',
                'verbose_name_plural': 'Bokningar',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='RepeatedBookingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='repeatgroup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.RepeatedBookingGroup'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
