# Generated by Django 2.1.2 on 2019-01-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='metadata_form',
            field=models.CharField(blank=True, choices=[(None, 'No metadata'), ('PI', 'Pi sauna')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='metadata',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
