# Generated by Django 2.0.3 on 2018-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
