# Generated by Django 2.0.3 on 2018-03-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='description',
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Timeslot'),
        ),
    ]
