# Generated by Django 2.0.3 on 2018-04-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180401_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='icon',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
