# Generated by Django 2.1.2 on 2018-12-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('booking', '0002_bookable_allowed_booker_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
