# Generated by Django 2.0.3 on 2018-03-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180315_1415'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('name', 'date', 'timeslot')},
        ),
    ]
