# Generated by Django 2.1.2 on 2019-02-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_booking_group'),
        ('booking', '0002_auto_20190120_1948'),
    ]

    operations = [
    ]
