# Generated by Django 2.0.3 on 2019-04-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190120_1948'),
        ('booking', '0003_booking_booking_group'),
    ]

    operations = [
    ]
