# Generated by Django 2.1.2 on 2019-02-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_merge_20190228_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookable',
            name='allowed_booker_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
