# Generated by Django 2.0.3 on 2018-04-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_user'),
        ('booking', '0004_auto_20180425_0854'),
    ]

    operations = [
    ]
