# Generated by Django 2.0.3 on 2018-09-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_merge_20180426_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='forward_limit_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookable',
            name='length_limit_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
