# Generated by Django 2.1.2 on 2019-05-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190228_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('callback_url', models.CharField(max_length=256)),
                ('bookable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Bookable')),
            ],
        ),
    ]
