# Generated by Django 2.0.3 on 2018-09-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_merge_20180426_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
