# Generated by Django 2.1.2 on 2019-05-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190228_1852'),
        ('booking', '0004_merge_20190403_1754'),
    ]

    operations = [
    ]
