# Generated by Django 2.0.3 on 2018-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookable_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookable',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
