# Generated by Django 2.1.2 on 2019-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('booking', '0006_merge_20190518_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='booking_restriction_groups',
            field=models.ManyToManyField(blank=True, related_name='restricted', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='allowed_booker_groups',
            field=models.ManyToManyField(blank=True, related_name='groupbooking', to='auth.Group'),
        ),
    ]
