# Generated by Django 2.1.2 on 2019-06-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190608_1053'),
        ('booking', '0006_externalservice'),
    ]

    operations = [
    ]
