# Generated by Django 2.0.3 on 2018-09-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20180905_1757'),
        ('booking', '0006_auto_20180914_2148'),
    ]

    operations = [
    ]
