# Generated by Django 2.0.3 on 2019-06-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('booking', '0008_merge_20190608_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='admin_groups',
            field=models.ManyToManyField(blank=True, related_name='admin', to='auth.Group'),
        ),
    ]
