# Generated by Django 2.0.3 on 2019-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_bookable_admin_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='metadata_form',
            field=models.CharField(blank=True, choices=[(None, 'No metadata'), ('PI', 'Pi sauna'), ('HB', 'Humpsbadet')], default=None, max_length=2, null=True),
        ),
    ]
