# Generated by Django 2.0.3 on 2018-10-01 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20181001_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookablerepeat',
            name='occurences',
        ),
        migrations.AddField(
            model_name='bookablerepeat',
            name='repeat_until',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
