# Generated by Django 2.0.3 on 2019-12-29 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20191110_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='bill_device_id',
            field=models.PositiveIntegerField(default=None, help_text='BILL device ID if BILL check is needed. If empty no BILL check will be performed', null=True),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='admin_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that have admin rights to this bookable.', related_name='admin', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='allowed_booker_groups',
            field=models.ManyToManyField(blank=True, help_text='Grupper som tillåts göra gruppbokningar för denna bookable', related_name='groupbooking', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='booking_restriction_groups',
            field=models.ManyToManyField(blank=True, help_text='Bokningar av denna bookable begränsas till medlemmar av dessa grupper. Ifall inga grupper definierats får alla inloggade användare boka.', related_name='restricted', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='forward_limit_days',
            field=models.PositiveIntegerField(default=0, help_text='Hur långt in i framtiden bokningar tillåts (noll betyder obegränsat)'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Gömmer bookablen från home viewn'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='id_str',
            field=models.CharField(help_text='Unik ID som används i URLen', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Endast alfanumeriska tecken är tillåtna')]),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='length_limit_hours',
            field=models.PositiveIntegerField(default=0, help_text='Max tillåtna längd för bokningar (noll betyder obegränsat)'),
        ),
    ]
