# Generated by Django 2.0.3 on 2018-10-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20181001_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookablerepeat',
            old_name='delay',
            new_name='frequency',
        ),
    ]
