# Generated by Django 2.0.3 on 2018-10-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20181002_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatedBookingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookablerepeat',
            name='booking',
        ),
        migrations.DeleteModel(
            name='BookableRepeat',
        ),
        migrations.AddField(
            model_name='booking',
            name='repeatgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.RepeatedBookingGroup'),
        ),
    ]
