# Generated by Django 3.1.2 on 2020-10-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20191229_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookable',
            name='bill_device_id',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='BILL device ID if BILL check is needed. If empty no BILL check will be performed', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='repeatgroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.repeatedbookinggroup'),
        ),
    ]
