# Generated by Django 3.2.12 on 2022-03-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20191229_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookable',
            name='bill_device_id',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='BILL device ID if BILL check is needed. If empty no BILL check will be performed', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='repeatgroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.repeatedbookinggroup'),
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('start_weekday', models.CharField(choices=[('1', 'måndag'), ('2', 'tisdag'), ('3', 'onsdag'), ('4', 'torsdag'), ('5', 'fredag'), ('6', 'lördag'), ('7', 'söndag')], max_length=1)),
                ('end_time', models.TimeField()),
                ('end_weekday', models.CharField(choices=[('1', 'måndag'), ('2', 'tisdag'), ('3', 'onsdag'), ('4', 'torsdag'), ('5', 'fredag'), ('6', 'lördag'), ('7', 'söndag')], max_length=1)),
                ('bookable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookable')),
            ],
        ),
    ]
