# Generated by Django 3.1.2 on 2020-10-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20201020_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('start_weekday', models.CharField(choices=[('Mon', 'måndag'), ('Tue', 'tisdag'), ('Wed', 'onsdag'), ('Thu', 'torsdag'), ('Fri', 'fredag'), ('Sat', 'lördag'), ('Sun', 'söndag')], max_length=3)),
                ('end_time', models.TimeField()),
                ('end_weekday', models.CharField(choices=[('Mon', 'måndag'), ('Tue', 'tisdag'), ('Wed', 'onsdag'), ('Thu', 'torsdag'), ('Fri', 'fredag'), ('Sat', 'lördag'), ('Sun', 'söndag')], max_length=3)),
                ('bookable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookable')),
            ],
        ),
    ]
