# Generated by Django 2.0.3 on 2018-10-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20181004_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='repeatgroup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.RepeatedBookingGroup'),
        ),
    ]
