# Generated by Django 3.1.2 on 2020-10-22 09:58

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20201020_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='booking_slots',
            field=models.JSONField(default=list, help_text='Timeslots that can be booked.', validators=[booking.validators.validate_booking_slots]),
        ),
    ]
