# Generated by Django 3.2.16 on 2023-01-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booking', '0012_auto_20220305_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookable',
            name='admin_groups',
            field=models.ManyToManyField(blank=True, help_text='Grupper med adminrättigheter till detta bokningsobjekt.', related_name='admin', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='allowed_booker_groups',
            field=models.ManyToManyField(blank=True, help_text='Grupper som tillåts göra gruppbokningar för detta bokningsobjekt', related_name='groupbooking', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='bill_device_id',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='BILL objekt ID om kontroll emot BILL behövs. Ingen kontroll görs om tomt.', null=True),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='booking_restriction_groups',
            field=models.ManyToManyField(blank=True, help_text='Bokningar av detta bokningsobjekt begränsas till medlemmar av dessa grupper. Ifall inga grupper definierats får alla inloggade användare boka.', related_name='restricted', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Gömmer bokningsobjektet från home viewn'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_weekday',
            field=models.CharField(choices=[('1', 'Måndag'), ('2', 'Tisdag'), ('3', 'Onsdag'), ('4', 'Torsdag'), ('5', 'Fredag'), ('6', 'Lördag'), ('7', 'Söndag')], max_length=1),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_weekday',
            field=models.CharField(choices=[('1', 'Måndag'), ('2', 'Tisdag'), ('3', 'Onsdag'), ('4', 'Torsdag'), ('5', 'Fredag'), ('6', 'Lördag'), ('7', 'Söndag')], max_length=1),
        ),
    ]
