# Generated by Django 3.2.16 on 2023-01-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20230120_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='google_calendar_event_location',
            field=models.CharField(blank=True, default='', help_text='The location to use for events created for the Google Calendar.', max_length=128),
        ),
        migrations.AddField(
            model_name='bookable',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='', help_text='If provided, bookings will be added to the Google Calendar with this ID. Make sure that the Google service account used for FARS has access to this calendar.', max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
