# Generated by Django 3.2.16 on 2023-02-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20230120_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='google_calendar_event_location',
            field=models.CharField(blank=True, default='', help_text='Platsen som används för Google Calendar händelserna.', max_length=128),
        ),
        migrations.AddField(
            model_name='bookable',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='', help_text='Bokningar läggs in i Google Calendarn med denna ID. Se till att Google service användarkontot som används av FARS har tillgång till denna kalender.', max_length=64),
        ),
        migrations.CreateModel(
            name='GCalEvent',
            fields=[
                ('event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
            ],
        ),
    ]
