# Generated by Django 3.2.16 on 2026-04-25 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booking', '0013_auto_20230120_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterField(
            model_name='bookable',
            name='admin_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that have admin rights to this bookable.', related_name='admin', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='allowed_booker_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that may be used to make group bookings for this bookable.', related_name='groupbooking', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='bill_device_id',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='BILL device ID if BILL check is needed. If empty no BILL check will be performed', null=True),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='booking_restriction_groups',
            field=models.ManyToManyField(blank=True, help_text='Bookings for this bookable are restricted to members of these groups. If no groups are defined, any authenticated user may book.', related_name='restricted', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='forward_limit_days',
            field=models.PositiveIntegerField(default=0, help_text='How far in the future bookings are allowed (zero means no limit)'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hides the bookable in the home view'),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='id_str',
            field=models.CharField(help_text='Unique ID string used in the URL', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='length_limit_hours',
            field=models.PositiveIntegerField(default=0, help_text='How long bookings are allowed to be (zero means no limit)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(max_length=128, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1),
        ),
    ]
