# Generated by Django 3.2.16 on 2023-02-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20230126_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCalEvent',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking.booking')),
                ('event_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='google_calendar_event_id',
        ),
        migrations.AlterField(
            model_name='bookable',
            name='google_calendar_event_location',
            field=models.CharField(blank=True, default='', help_text='Platsen som används för Google Calendar händelserna.', max_length=128),
        ),
        migrations.AlterField(
            model_name='bookable',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='', help_text='Bokningar läggs in i Google Calendarn med denna ID. Se till att Google service användarkontot som används av FARS har tillgång till denna kalender.', max_length=64),
        ),
    ]
